### PR TITLE
Update to TensorFlow.js 4.13.0

### PR DESCRIPTION
**Pull request by reillyeon**
Companion to https://github.com/webmachinelearning/webnn-polyfill/pull/233 to keep everything on the same TensorFlow.js version.

### CODE REVIEW

**Comment by reillyeon** [comment]
@huningxin, @BruceDai, @Honry, please take a look.

**Review by huningxin — APPROVED** [review]
LGTM, thanks!

**Review by Honry — APPROVED** [review]
LGTM, thanks!

**Comment by reillyeon** [comment]
Can you merge this change? I don't have permissions on this repository.

**Pull request merged**
