### PR TITLE
Remove deprecated MLOperandDescriptor.type

### PR DESCRIPTION
**Pull request by Honry**
Now latest Chrome has supported MLOperandDescriptor.dataType, we can remove deprecated MLOperandDescriptor.type.

### CODE REVIEW

**Comment by Honry** [comment]
@ibelem, @huningxin, PTAL, thanks!

cc/ @BruceDai, you may want to remove it from webnn-polyfill as well.

**Review by huningxin — APPROVED** [review]
LGTM!

**Comment by BruceDai** [comment]
> cc/ @BruceDai, you may want to remove it from webnn-polyfill as well.

Thanks for kindly reminder. 👍 
WebNN Polyfill API [has already supported `MLOperandDescriptor.dataType`](https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/operand.ts#L22) since https://github.com/webmachinelearning/webnn-polyfill/pull/238 was landed.

**Comment by Honry** [comment]
> > cc/ @BruceDai, you may want to remove it from webnn-polyfill as well.
> 
> Thanks for kindly reminder. 👍 WebNN Polyfill API [has already supported `MLOperandDescriptor.dataType`](https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/operand.ts#L22) since [webmachinelearning/webnn-polyfill#238](https://github.com/webmachinelearning/webnn-polyfill/pull/238) was landed.

Oh, so remaining the WPT tests I think.

**Comment by BruceDai** [comment]
Right. I will submit PR to fix it on WPT side. Thanks.

**Pull request merged**
