### PR TITLE
Split transposed convolution to convTranspose2d

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
Depends on https://github.com/webmachinelearning/test-data/pull/15, @huningxin, @BruceDai, PTAL, thanks!

**Comment by BruceDai** [comment]
@Honry Please also update `DEPS` file using latest https://github.com/webmachinelearning/test-data/commit/d9f1537096b0fcbbef0889b540bf8ce6c8833969

**Comment by Honry** [comment]
@BruceDai, thanks for your reminder! I will update it soon.

**Comment by Honry** [comment]
@BruceDai, the test-data submodule has been updated.

**Comment by BruceDai** [comment]
Great, thanks @Honry

**Pull request merged**
