### PR TITLE
Fixed gemm with 2-D optional third input in mobilenetv2 nchw model.

### LINKED ISSUE #47: [Gemm] only support 2d tensor
The bias is 1D tensor that isn't supported in WebNN, please reshape it to 2D like [native implementation](https://github.com/otcshare/webnn-native/blob/main/examples/MobileNetV2/MobileNetV2.cpp#L121)

https://github.com/webmachinelearning/webnn-samples/blob/master/image_classification/mobilenet_nchw.js#L44
`const bias = await buildConstantByNpy(this.builder_, biasName);`

### PR DESCRIPTION
**Pull request by BruceDai**
This pr is to fix #47. Link https://github.com/webmachinelearning/webnn-polyfill/issues/68.
@huningxin @Honry PTAL, thank.

### CODE REVIEW

**Review by Honry — APPROVED** [review]
Thanks for the fixing! LGTM.

**Comment by huningxin** [comment]
Opened webmachinelearning/webnn#171 , let's wait for that issue to be closed.

**Comment by huningxin** [comment]
[gemm](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm) now supports scalar and broadcasting.

**Comment by BruceDai** [comment]
Close it, since spec for third input of gemm ops supported scalar and broadcasting.

**Pull request closed without merging**
