### PR TITLE
Add the homepage

### PR DESCRIPTION
**Pull request by Honry**
This will help centralize WebNN samples in Electron app
with a directable index.html, thus we don't have to build
multiple WebNN samples in WebNN-native Electron examples.

### CODE REVIEW

**Comment by Honry** [comment]
Preview: https://honry.github.io/webnn-samples/

@ibelem, @huningxin, PTAL, thanks!

**Comment by ibelem** [comment]
Thanks @Honry !

1. Could you please change the font-family of the svg logo?
2. The beauty of the UI usually lies in the details. To put it bluntly, it is the feeling of pixels. 
c

**Comment by Honry** [comment]
@ibelem, thanks for your comments, PTAL again!

For redirecting to homepage, currently I hide the link in logo icon, do we need a new button for home page?

**Comment by ibelem** [comment]
No strong opinion. Thanks a lot @Honry !

**Comment by Honry** [comment]
Thanks @ibelem! I am going to merge it to unblock further development.

**Pull request merged**
