### PR TITLE
Optimize the README

### PR DESCRIPTION
**Pull request by mingmingtasd**
PTAL, thanks! @ibelem

### CODE REVIEW

**Comment by ibelem** [comment]
@mingmingtasd  Because the requirement for GPU and NPU are different, we'd better to describe detailed requirement for CPU/GPU and NPU in following format: 

### WebNN Installation Guides

#### Running WebNN on CPU and GPU

Requirement description + GPU driver links.
- Steps

#### Running WebNN on NPU
Requirement description + NPU driver links.
- Steps

@huningxin

**Comment by mingmingtasd** [comment]
@ibelem Updated as we discussed, ptal, thanks!

**Comment by ibelem** [comment]
LGTM, we can remove note of "NPU intermittent issue" later. @huningxin  PTAL

**Review by ibelem — APPROVED** [review]

**Review by ibelem — CHANGES_REQUESTED** [review]
Go to "%LOCALAPPDATA%\Microsoft\Edge SxS\User Data", check the "EdgeOnnxRuntimeDirectML<version>\DirectML.dll" exists
"%LOCALAPPDATA%" means "C:\Users<username>\AppData\Local"

@mingmingtasd Please fix the path issue in preview mode.

**Comment by mingmingtasd** [comment]
> Go to "%LOCALAPPDATA%\Microsoft\Edge SxS\User Data", check the "EdgeOnnxRuntimeDirectML\DirectML.dll" exists "%LOCALAPPDATA%" means "C:\Users\AppData\Local"
> 
> @mingmingtasd Please fix the path issue in preview mode.

Done. @ibelem

**Review by ibelem — APPROVED** [review]
LGTM now, thanks @mingmingtasd . @huningxin  PTAL

**Review by huningxin — APPROVED** [review]
LGTM

**Pull request merged**
