### PR TITLE
Fixed unexpected error during model switch

### PR DESCRIPTION
**Pull request by Honry**
When switch model before last inference done, error: `cannot read property * of null` will be thrown.

This is because the model instance is changed suddenly when doing load/build/compute operation. To avoid this, I added a overlay to the model loading ui thus user couldn't interrupt the operations.

Besides, make first time loading with no model selected by default, to help user easily choose expected model to experience.

### CODE REVIEW

**Comment by Honry** [comment]
@huningxin, @mingmingtasd, PTAL, thanks!

**Comment by Honry** [comment]
Check preview at https://honry.github.io/webnn-samples/.

**Comment by huningxin** [comment]
@ibelem , could you please take a look? Thanks!

**Comment by ibelem** [comment]
Thanks @Honry to fix the UE issue, I don't like the gray mask on the front to prevent users to click other buttons during the loading-compilation-infernecing process, but it fixed the error issue described in the issue. I plan to improve all the UI of webnn-sample in the future, after the onewebmeet demo.

**Comment by huningxin** [comment]
Thanks for the fix @Honry and the review @ibelem !

**Pull request merged**
