### PR TITLE
Make sure video output is synchronous

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@huningxin, PTAL, thanks!

**Comment by huningxin** [comment]
@ibelem, could you please help take a look? Thanks.

**Comment by ibelem** [comment]
Thanks @Honry ! I am not confident by introducing an extra canvas via getVideoFrame(videoElement) to solve this issue, will think about how to improve this by leveraging Media Transform API and relevant post-processing solutions.

**Comment by Honry** [comment]
Thanks @ibelem! I will merge it as is.

**Pull request merged**
