### PR TITLE
Add facial landmark detection sample

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@ibelem, @BruceDai, PTAL, thanks! I will create a preview once corresponding [test-data](https://github.com/webmachinelearning/test-data/pull/16) is landed.

**Comment by Honry** [comment]
Preview: https://honry.github.io/webnn-samples/facial_landmark_detection/index.html

@huningxin, @ibelem, @BruceDai, PTAL, thanks!

**Comment by BruceDai** [comment]
Great job, Thanks @Honry. LTGM.

**Review by huningxin — APPROVED** [review]
LGTM, thanks @Honry !

**Pull request merged**
