### PR TITLE
Support webnn and polyfill switch in one page

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
Preview: https://honry.github.io/webnn-samples/image_classification/index.html

@ibelem, @BruceDai, PTAL, thanks!

**Comment by BruceDai** [comment]
Thanks @Honry. This patch would help user clearly see which backend are available to run sample.

I ran your preview sample both on Stable Chrome browser and Chromium browser integrated with WebNN API,

1. on Stable Chrome browser, we can run sample by **Wasm (CPU)** and **WebGL (GPU)** backend,
2. on Chromium browser integrated with WebNN API, we can run sample by **WebNN (CPU)** and **WebNN (GPU)** backend

There's a nit of promotion "Please select model and layout to start prediction.", please update it by "Please select backend, model and layout to start prediction."  WDYT?

**Comment by Honry** [comment]
@BruceDai, thanks much for your review!

> There's a nit of promotion "Please select model and layout to start prediction.", please update it by "Please select backend, model and layout to start prediction." WDYT?

Actually only the model is not selected, it may be better to use 'Please select model to start prediction', same as https://intel.github.io/webml-polyfill/examples/image_classification/?prefer=none&b=WASM&m=none&s=image&d=0&f=WebNN. WTYD?

**Comment by BruceDai** [comment]
> Actually only the model is not selected, it may be better to use 'Please select model to start prediction'

@Honry SGTM, thanks.

**Comment by Honry** [comment]
@BruceDai, thanks! I am going to merge it.

**Pull request merged**
