### PR TITLE
[NNotepad] Fix #253 e.target.close is not a function error

### LINKED ISSUE #253: [NNotepad] e.target.close is not a function when click close button in generated code and help dialogs
Repro Steps:

1. Open Developer Tools -> Console
1. Visit https://webmachinelearning.github.io/webnn-samples/nnotepad/
2. Click "Show generated code" or "Show documentation" button
3. Click "Close" button

Actual Result:
e.target.close is not a function

Screenshot 2024-06-19 124850

### PR DESCRIPTION
**Pull request by ibelem**
Fix #253

Click "Close" button in "Show generated code" or "Show documentation" dialog not only triggers button click event but also the dialog click event, which makes the e.target in dialog click event quals the dialog element and button element, but there is no close() method for buttons.

@inexorabletash @anssiko @Honry PTAL

### CODE REVIEW

**Review by Honry — APPROVED** [review]
LGTM, thanks!

**Review by inexorabletash — APPROVED** [review]
This is fine, but I think you could also do `if (e.target !== dialog) return;`

Sorry about this - obviously I added the "click outside to close" later and didn't test that the buttons still worked.

**Comment by ibelem** [comment]
Thanks @inexorabletash , `if (e.target !== dialog) return;` is much more concise and precise, PTAL.

**Review by inexorabletash — APPROVED** [review]
LGTM thanks!

**Pull request merged**
