### PR TITLE
Update according to spec and polyfill changes

### LINKED ISSUE #17: Update the samples with new ModelBuilder and Execution API.

### PR DESCRIPTION
**Pull request by huningxin**
fix #17 

The preview version is: 
* [LeNet](https://huningxin.github.io/webnn-samples/lenet/)
* [Code Editor](https://huningxin.github.io/webnn-samples/code/)

Another improvement is to support "example" search parameter in Code Editor example. This feature could help embed a link of a specific example. I also added some new examples for new execution API. 

For example:
1. The default example of the spec: https://huningxin.github.io/webnn-samples/code/?example=simple_graph.js
2. The example of returning outputs: https://huningxin.github.io/webnn-samples/code/?example=matmul.js
3. The example of pre-allocated outputs: https://huningxin.github.io/webnn-samples/code/?example=preallocated_outputs.js
4. The example of inputs with dynamic shape: https://huningxin.github.io/webnn-samples/code/?example=dynamic_shape.js
5. The example of optional outputs: https://huningxin.github.io/webnn-samples/code/?example=dynamic_shape.js

@anssiko @wchao1115 @pyu10055 @BruceDai , please take a look. Thanks!

### CODE REVIEW

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
As a side comment, we should probably link some of these code editor examples from the explainer once landed.

**Comment by huningxin** [comment]
> As a side comment, we should probably link some of these code editor examples from the explainer once landed.

It's a great idea. Please note there are two PRs (https://github.com/webmachinelearning/webnn/pull/104 and https://github.com/webmachinelearning/webnn/pull/111) to align the example code in spec and explainer to the samples here.

**Comment by huningxin** [comment]
I updated the PR according to webnn-polyfill change https://github.com/webmachinelearning/webnn-polyfill/pull/25. Please take another look. Thanks!

**Comment by huningxin** [comment]
webmachinelearning/webnn-polyfill#25 merged and deployed. @BruceDai , please help take another look. If no issues, we can merge and deploy this PR.

**Comment by BruceDai** [comment]
Awesome samples. 
Verified, two samples both work well, thanks @huningxin

**Review by BruceDai — APPROVED** [review]

**Comment by huningxin** [comment]
Thanks for review and approval. I'm going to merge and deploy this PR.

**Pull request merged**
